import { useCallback, useEffect, useState } from 'react'
import { deleteExperiment, getExperiment, getExperimentObservations, listExperiments } from '../api.js'
import ObservationTable from './ObservationTable.jsx'
import SourceBadge from './SourceBadge.jsx'

const OBSERVATION_LIMIT = 1000

const OBSERVATION_COLUMNS = [
  { name: 'culture_time_hours', label: 'Culture time', unit: 'h', type: 'number' },
  { name: 'temperature_c', label: 'Temperature', unit: '°C', type: 'number' },
  { name: 'ph', label: 'pH', type: 'number' },
  { name: 'dissolved_oxygen_percent', label: 'DO', unit: '% air sat.', type: 'number' },
  { name: 'agitation_rpm', label: 'Agitation', unit: 'rpm', type: 'number' },
  { name: 'cell_density', label: 'Cell density', unit: '×10⁶ cells/mL', type: 'number' },
]

const formatDate = (iso) => new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })

function ExperimentDetail({ experimentId, version, onClose }) {
  const [experiment, setExperiment] = useState(null)
  const [observations, setObservations] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false
    Promise.all([getExperiment(experimentId), getExperimentObservations(experimentId, OBSERVATION_LIMIT)])
      .then(([exp, obs]) => {
        if (cancelled) return
        setExperiment(exp)
        setObservations(obs)
        setError(null)
      })
      .catch((err) => !cancelled && setError(err.message))
    return () => {
      cancelled = true
    }
  }, [experimentId, version])

  return (
    <div className="history-detail">
      <div className="card-header">
        <h3>Experiment {experimentId}</h3>
        <button className="secondary small" onClick={onClose}>
          Close
        </button>
      </div>
      {error && <div className="alert alert-error">{error}</div>}
      {experiment && (
        <>
          <dl className="details">
            <dt>Name</dt>
            <dd>{experiment.name}</dd>
            <dt>Data source</dt>
            <dd>
              <SourceBadge source={experiment.data_source} />
            </dd>
            <dt>Scale</dt>
            <dd>{experiment.scale_liters} L</dd>
            <dt>Created</dt>
            <dd>{formatDate(experiment.created_at)}</dd>
            <dt>Observations</dt>
            <dd>{experiment.observation_count}</dd>
            {experiment.description && (
              <>
                <dt>Description</dt>
                <dd>{experiment.description}</dd>
              </>
            )}
            {experiment.notes && (
              <>
                <dt>Notes</dt>
                <dd>{experiment.notes}</dd>
              </>
            )}
          </dl>
          {experiment.data_source === 'simulated' && (
            <p className="muted small-note">
              Simulated observations are generated by software and are not laboratory measurements.
            </p>
          )}
        </>
      )}
      {observations?.length === 0 && <p className="muted placeholder">This experiment has no observations yet.</p>}
      {observations?.length > 0 && (
        <div className="table-scroll">
          <ObservationTable
            title={
              experiment && experiment.observation_count > observations.length
                ? `Observations (first ${observations.length} of ${experiment.observation_count})`
                : `Observations (${observations.length})`
            }
            fields={OBSERVATION_COLUMNS}
            observations={observations}
          />
        </div>
      )}
    </div>
  )
}

export default function ExperimentHistory({ active, dataVersion, onDataChanged, onOpenAnalysis }) {
  const [experiments, setExperiments] = useState(null)
  const [error, setError] = useState(null)
  const [message, setMessage] = useState(null)
  const [selectedId, setSelectedId] = useState(null)
  const [confirmingId, setConfirmingId] = useState(null)
  const [refreshCount, setRefreshCount] = useState(0)

  const load = useCallback(() => {
    listExperiments()
      .then((list) => {
        setExperiments(list)
        setError(null)
      })
      .catch((err) => setError(`Could not load experiments: ${err.message}`))
  }, [])

  // Reload whenever the page is shown or data changes elsewhere (e.g. a simulator run is saving).
  useEffect(() => {
    if (active) load()
  }, [active, dataVersion, refreshCount, load])

  async function handleDelete(experimentId) {
    setConfirmingId(null)
    setMessage(null)
    try {
      const result = await deleteExperiment(experimentId)
      setMessage({ type: 'success', text: result.message })
      if (selectedId === experimentId) setSelectedId(null)
      onDataChanged?.()
    } catch (err) {
      setMessage({ type: 'error', text: `Delete failed: ${err.message}` })
    }
    load()
  }

  return (
    <section className="card history">
      <div className="card-header">
        <h2>Experiment History</h2>
        <button className="secondary small" onClick={() => setRefreshCount((n) => n + 1)}>
          Refresh
        </button>
      </div>

      {error && <div className="alert alert-error">{error}</div>}
      {message && (
        <div className={`alert alert-${message.type}`} role="status">
          {message.text}
        </div>
      )}
      {experiments?.length === 0 && (
        <p className="muted placeholder">No experiments yet. Create one on the Experiment Data or Simulated Bioreactor page.</p>
      )}

      {experiments?.length > 0 && (
        <div className="table-wrap">
          <table className="history-table">
            <thead>
              <tr>
                <th>Experiment ID</th>
                <th>Name</th>
                <th>Scale</th>
                <th>Data source</th>
                <th>Created</th>
                <th>Observations</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {experiments.map((e) => (
                <tr key={e.experiment_id} className={e.experiment_id === selectedId ? 'row-selected' : undefined}>
                  <td>
                    <code>{e.experiment_id}</code>
                  </td>
                  <td>{e.name}</td>
                  <td className="num">{e.scale_liters} L</td>
                  <td>
                    <SourceBadge source={e.data_source} />
                  </td>
                  <td>{formatDate(e.created_at)}</td>
                  <td className="num">{e.observation_count}</td>
                  <td>
                    <div className="row-actions">
                      {confirmingId === e.experiment_id ? (
                        <>
                          <span className="muted">Delete with all observations?</span>
                          <button className="danger small" onClick={() => handleDelete(e.experiment_id)}>
                            Yes, delete
                          </button>
                          <button className="secondary small" onClick={() => setConfirmingId(null)}>
                            Cancel
                          </button>
                        </>
                      ) : (
                        <>
                          <button className="secondary small" onClick={() => onOpenAnalysis?.(e.experiment_id)}>
                            Analyze
                          </button>
                          <button className="secondary small" onClick={() => setSelectedId(e.experiment_id)}>
                            View
                          </button>
                          <button className="secondary small" onClick={() => setConfirmingId(e.experiment_id)}>
                            Delete
                          </button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {selectedId && (
        <ExperimentDetail
          key={selectedId}
          experimentId={selectedId}
          version={`${dataVersion}-${refreshCount}-${active}`}
          onClose={() => setSelectedId(null)}
        />
      )}
    </section>
  )
}
