"""Phase 19A: deterministic SIMULATED demo seed (developer CLI; never run by the application)."""

import os
import subprocess
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import inspect
from sqlmodel import Session

from app import db, demo_seed
from app import repository as repo
from app.main import app
from app.precedents import PrecedentQuery, find_precedents
from app.simulator_api import check_save_target

client = TestClient(app)
BACKEND = Path(__file__).resolve().parents[1]


def seed(replace=False):
    with Session(db.engine) as s:
        return demo_seed.seed_demo(s, replace=replace)


def snapshot():
    """Experiment metadata + observation values (no ids/timestamps) for the demo experiments."""
    with Session(db.engine) as s:
        out = {}
        for i in demo_seed.DEMO_IDS:
            row = repo.get_experiment(s, i)
            obs = [repo.to_observation_read(o).model_dump(exclude={"id", "recorded_at"}) for o in repo.list_observations(s, i)]
            out[i] = (row.name, row.description, row.scale_liters, row.data_source, obs) if row else None
        return out


def experiments():
    return {e["experiment_id"]: e for e in client.get("/api/experiments").json()}


def test_creates_exactly_four_simulated_labelled_experiments():
    seed()
    exps = experiments()
    assert set(exps) == set(demo_seed.DEMO_IDS)
    assert all(e["data_source"] == "simulated" for e in exps.values())
    assert {i: e["scale_liters"] for i, e in exps.items()} == {
        "DEMO-1L-BASELINE": 1, "DEMO-10L-SCALEUP": 10, "DEMO-1L-DO-EVENT": 1, "DEMO-LIVE": 1}
    for i, e in exps.items():
        assert e["description"].startswith("SIMULATED DEMO DATA — generated by the software simulator (seed ")
        assert "not laboratory measurements" in e["description"]
    assert "does not model physical scale effects" in exps["DEMO-10L-SCALEUP"]["description"]
    assert "empty" in exps["DEMO-LIVE"]["description"].lower()


def test_observation_counts_and_duration():
    seed()
    exps = experiments()
    for i in ("DEMO-1L-BASELINE", "DEMO-10L-SCALEUP", "DEMO-1L-DO-EVENT"):
        assert exps[i]["observation_count"] == 192
    obs = client.get("/api/experiments/DEMO-1L-BASELINE/observations").json()
    assert obs[0]["culture_time_hours"] == 0 and obs[-1]["culture_time_hours"] == 95.5
    scale = client.get("/api/experiments/DEMO-10L-SCALEUP/observations").json()
    assert abs(scale[0]["agitation_rpm"] - 140) < 0.01 and abs(obs[0]["agitation_rpm"] - 180) < 0.01  # configured setpoints


def test_do_event_note_and_significant_precedent():
    seed()
    obs = client.get("/api/experiments/DEMO-1L-DO-EVENT/observations").json()
    noted = [o for o in obs if (o["notes"] or "").startswith("SIMULATED DISTURBANCE")]
    assert [o["culture_time_hours"] for o in noted] == [24.0] and "dissolved_oxygen_percent -35" in noted[0]["notes"]
    with Session(db.engine) as s:
        r = find_precedents(s, PrecedentQuery(type="sudden_change", parameter="dissolved_oxygen_percent", direction="decreased"))
    hits = [p for p in r.precedents if p.experiment_id == "DEMO-1L-DO-EVENT"]
    assert len(hits) == 1 and hits[0].severity == "significant" and hits[0].trigger_time_hours == 24.0
    assert all(p.experiment_id == "DEMO-1L-DO-EVENT" for p in r.precedents)  # the undisturbed runs have no such finding


def test_demo_live_is_empty_and_a_valid_save_target():
    seed()
    assert experiments()["DEMO-LIVE"]["observation_count"] == 0
    assert check_save_target("DEMO-LIVE") == 1.0


def test_deterministic_generation_and_fresh_databases():
    runs = {r.experiment_id: r for r in demo_seed.DEMO_RUNS}
    for i in ("DEMO-1L-BASELINE", "DEMO-10L-SCALEUP", "DEMO-1L-DO-EVENT"):
        assert demo_seed.demo_observations(runs[i]) == demo_seed.demo_observations(runs[i])
    seed()
    first = snapshot()
    db.SQLModel.metadata.drop_all(db.engine)  # a fresh, empty database
    db.init_db()
    seed()
    assert snapshot() == first


def test_second_run_without_replace_changes_nothing():
    seed()
    before = snapshot()
    report = seed()
    assert all("already present, unchanged" in line for line in report)
    assert snapshot() == before


def test_existing_live_run_needs_replace():
    seed()
    live = demo_seed.demo_observations(demo_seed.DEMO_RUNS[0])[:1]  # as the simulator would save a live observation
    with Session(db.engine) as s:
        repo.add_observations(s, "DEMO-LIVE", live)
    report = seed()
    assert any("DEMO-LIVE" in line and "use --replace" in line for line in report)
    assert experiments()["DEMO-LIVE"]["observation_count"] == 1  # not deleted in default mode
    seed(replace=True)
    assert experiments()["DEMO-LIVE"]["observation_count"] == 0


def test_replace_rebuilds_only_demo_ids_and_keeps_other_data():
    for i in ("EXP-DEMO-001", "EXP-DEMO-002", "USER-RUN"):
        assert client.post("/api/experiments", json={"experiment_id": i, "name": i, "scale_liters": 1, "data_source": "manual"}).status_code == 201
    seed()
    before = snapshot()
    report = seed(replace=True)
    assert all("rebuilt" in line for line in report)
    assert snapshot() == before  # rebuilt deterministically
    assert {"EXP-DEMO-001", "EXP-DEMO-002", "USER-RUN"} <= set(experiments())


@pytest.mark.parametrize("replace", [False, True])
def test_conflicting_non_demo_experiment_is_never_deleted(replace):
    body = {"experiment_id": "DEMO-1L-BASELINE", "name": "My real run", "scale_liters": 1, "data_source": "manual"}
    assert client.post("/api/experiments", json=body).status_code == 201
    with pytest.raises(demo_seed.DemoSeedConflict):
        seed(replace=replace)
    exps = experiments()
    assert set(exps) == {"DEMO-1L-BASELINE"} and exps["DEMO-1L-BASELINE"]["name"] == "My real run"  # nothing changed


def test_simulated_experiment_without_marker_is_a_conflict():
    body = {"experiment_id": "DEMO-LIVE", "name": "x", "scale_liters": 1, "data_source": "simulated", "description": "my run"}
    assert client.post("/api/experiments", json=body).status_code == 201
    with pytest.raises(demo_seed.DemoSeedConflict):
        seed(replace=True)
    assert experiments()["DEMO-LIVE"]["description"] == "my run"


def test_schema_unchanged():
    tables = set(inspect(db.engine).get_table_names())
    seed(replace=True)
    assert set(inspect(db.engine).get_table_names()) == tables == {"experiments", "observations"}


def test_application_startup_does_not_seed():
    with TestClient(app) as started:  # runs the FastAPI lifespan (init_db)
        assert started.get("/api/experiments").json() == []
    source = (BACKEND / "app" / "main.py").read_text(encoding="utf-8")
    assert "demo_seed" not in source


def test_cli_seeds_configured_database(tmp_path):
    url = f"sqlite:///{(tmp_path / 'cli.db').as_posix()}"
    env = {**os.environ, "BIOPROCESS_DB_URL": url, "PYTHONIOENCODING": "utf-8"}
    run = lambda *a: subprocess.run([sys.executable, "-m", "app.demo_seed", *a], cwd=BACKEND, env=env,  # noqa: E731
                                    capture_output=True, text=True, encoding="utf-8", timeout=120)
    first = run()
    assert first.returncode == 0 and "DEMO-LIVE: created (0 observations)" in first.stdout
    assert "not laboratory measurements" in first.stdout
    second = run()
    assert second.returncode == 0 and second.stdout.count("already present, unchanged") == 4
    assert run("--replace").stdout.count("rebuilt") == 4
