"""Deterministic SIMULATED demo dataset (Phase 19A). Developer/demo CLI only.

    cd backend
    .venv\\Scripts\\python -m app.demo_seed            # safe: creates missing demo experiments, changes nothing else
    .venv\\Scripts\\python -m app.demo_seed --replace  # rebuilds ONLY the four demo experiments below

Uses the configured database (BIOPROCESS_DB_URL or backend/data/bioprocess.db) through the existing
repository functions, and the existing software simulator for the observations. It is never imported
or run by the application itself. The data is simulated and is not laboratory data.
"""

import argparse
import sys
from dataclasses import dataclass

from sqlmodel import Session

from . import db
from . import repository as repo
from .models import DataSource, ExperimentCreate, Observation
from .simulator import BioreactorSimulator, SimulatorConfig

MARKER = "SIMULATED DEMO DATA — generated by the software simulator"
STEPS = 192  # 192 × 0.5 h = 96 h of culture time (0 – 95.5 h)
HOURS_PER_STEP = 0.5


@dataclass(frozen=True)
class DemoRun:
    experiment_id: str
    name: str
    scale_liters: int
    seed: int
    detail: str
    agitation_rpm: float = 180.0
    disturbance_at_step: int | None = None  # SIMULATED DISTURBANCE applied before this step
    disturbance: tuple[str, float] | None = None
    empty: bool = False

    @property
    def description(self) -> str:
        return f"{MARKER} (seed {self.seed}); not laboratory measurements. {self.detail}"


DEMO_RUNS = (
    DemoRun("DEMO-1L-BASELINE", "Demo 1 L baseline run (simulated)", 1, 101,
            "Reference run with the simulator's default setpoints (agitation 180 rpm), 96 h."),
    DemoRun("DEMO-10L-SCALEUP", "Demo 10 L scale-up run (simulated)", 10, 102,
            "Same simulator model with a configured agitation setpoint of 140 rpm, 96 h. The simulator does not model "
            "physical scale effects: differences from the 1 L run come from the configured setpoint and the random seed.",
            agitation_rpm=140.0),
    DemoRun("DEMO-1L-DO-EVENT", "Demo 1 L run with a DO event (simulated)", 1, 103,
            "Default setpoints, 96 h, with a SIMULATED DISTURBANCE of dissolved oxygen −35 % air sat. at 24 h "
            "(software-injected; recorded in the observation notes). Used as a precedent in the live demo.",
            disturbance_at_step=48, disturbance=("dissolved_oxygen_percent", -35.0)),
    DemoRun("DEMO-LIVE", "Demo live run target (simulated, empty)", 1, 104,
            "Empty SIMULATED experiment used as the save target for the live simulator demonstration.",
            empty=True),
)
DEMO_IDS = tuple(r.experiment_id for r in DEMO_RUNS)


class DemoSeedConflict(Exception):
    """A demo ID is used by an experiment that is not seeded demo data; nothing was changed."""


def demo_observations(run: DemoRun) -> list[Observation]:
    """Deterministic observations from the existing simulator (fixed seed and step count)."""
    if run.empty:
        return []
    config = SimulatorConfig(experiment_id=run.experiment_id, volume_liters=run.scale_liters, agitation_rpm=run.agitation_rpm,
                             hours_per_step=HOURS_PER_STEP, seed=run.seed)
    sim = BioreactorSimulator(config, run.experiment_id)
    observations = []
    for step in range(STEPS):
        if step == run.disturbance_at_step:
            sim.apply_disturbance(*run.disturbance)
        observations.append(sim.step())
    return observations


def is_seeded_demo(row) -> bool:
    return (row.experiment_id in DEMO_IDS and row.data_source == DataSource.SIMULATED.value
            and (row.description or "").startswith(MARKER))


def seed_demo(session: Session, replace: bool = False) -> list[str]:
    """Create the demo experiments; with `replace`, rebuild them. Returns report lines.

    Raises DemoSeedConflict (before any change) if a demo ID belongs to a non-demo experiment.
    """
    existing = {r.experiment_id: repo.get_experiment(session, r.experiment_id) for r in DEMO_RUNS}
    conflicts = [i for i, row in existing.items() if row is not None and not is_seeded_demo(row)]
    if conflicts:
        raise DemoSeedConflict(
            f"Refusing to seed: {', '.join(conflicts)} already exist(s) but are not seeded SIMULATED demo data "
            "(data source and description marker do not match). Nothing was changed."
        )
    report = []
    for run in DEMO_RUNS:
        row = existing[run.experiment_id]
        if row is not None and not replace:
            count = repo.count_observations(session, run.experiment_id)
            line = f"{run.experiment_id}: already present, unchanged ({count} observations)."
            if run.empty and count:
                line += " It already holds a live run; use --replace before saving another live run to it."
            report.append(line)
            continue
        if row is not None:
            repo.delete_experiment(session, row)
        repo.create_experiment(session, ExperimentCreate(
            experiment_id=run.experiment_id, name=run.name, description=run.description,
            scale_liters=run.scale_liters, data_source=DataSource.SIMULATED,
        ))
        observations = demo_observations(run)
        if observations:
            repo.add_observations(session, run.experiment_id, observations)
        report.append(f"{run.experiment_id}: {'rebuilt' if row is not None else 'created'} ({len(observations)} observations).")
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.demo_seed", description="Seed the SIMULATED demo dataset.")
    parser.add_argument("--replace", action="store_true", help="Delete and recreate ONLY the four DEMO-* demo experiments.")
    args = parser.parse_args(argv)
    for stream in (sys.stdout, sys.stderr):  # never fail on a console that cannot encode "—"
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(errors="replace")
    db.init_db()
    print(f"Database: {db.engine.url.render_as_string(hide_password=True)}")
    print("SIMULATED DEMO DATA - software-generated, not laboratory measurements.")
    try:
        with db.session_scope() as session:
            for line in seed_demo(session, replace=args.replace):
                print("  " + line)
    except DemoSeedConflict as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
