"""Evidence-linked AI (Phase 21): application-generated evidence IDs for Gemini to cite.

The deterministic layers stay the source of facts. Before a Gemini call, the findings and
process statistics that are actually sent are given response-scoped IDs (``F-001`` for
anomaly findings, in their existing most-severe-first order; ``P-001`` for process
statistics and data coverage, in analysis order). The IDs are written into the same
context Gemini already receives, so nothing is duplicated. Gemini may only cite these
IDs; unknown references are removed before the response is returned. Nothing is stored.
"""

from typing import Literal

from pydantic import BaseModel

from .analysis import ExperimentAnalysis
from .anomaly import Finding

EvidenceSource = Literal["deterministic_anomaly_detection", "deterministic_process_analysis"]

PROMPT_RULES = """Evidence IDs:
- Items in the context carry an "evidence_id" (F-### = deterministic anomaly finding, P-### = deterministic process
  statistic; data_coverage_evidence_id = the data-coverage summary). These IDs were generated by the application before this request; they are the ONLY
  valid evidence IDs.
- Cite the evidence_id values that support each claim in the evidence_refs fields. Never invent, alter or guess an ID,
  and never cite an ID for a claim it does not support.
- A claim without supporting evidence must be stated as an interpretation or as uncertain, with no evidence_refs."""


class EvidenceItem(BaseModel):
    """One deterministic fact the AI may cite. Only data the application already computed."""

    id: str
    type: Literal["anomaly", "process_statistic", "data_coverage"]
    source: EvidenceSource
    description: str
    parameter: str | None = None
    parameter_label: str | None = None
    unit: str | None = None
    finding_type: str | None = None  # anomaly type label, e.g. "Rapid parameter change"
    severity: Literal["info", "attention", "significant"] | None = None
    direction: str | None = None
    culture_time_start: float | None = None
    culture_time_end: float | None = None
    observed_value: float | None = None
    previous_value: float | None = None
    minimum: float | None = None
    maximum: float | None = None


def _finding_item(i: int, f: Finding) -> EvidenceItem:
    start, end = f.previous_time_hours, f.culture_time_hours
    if start is None:
        start = end
    return EvidenceItem(
        id=f"F-{i:03d}",
        type="anomaly",
        source="deterministic_anomaly_detection",
        description=f.message,
        parameter=f.parameter,
        parameter_label=f.parameter_label,
        unit=f.unit,
        finding_type=f.type_label,
        severity=f.severity.value if hasattr(f.severity, "value") else f.severity,
        direction=f.direction,
        culture_time_start=start,
        culture_time_end=end,
        observed_value=f.observed_value,
        previous_value=f.previous_value,
    )


def build_evidence(analysis: ExperimentAnalysis, findings: list[Finding]) -> list[EvidenceItem]:
    """Deterministic evidence for the findings and statistics that are sent to Gemini."""
    items = [_finding_item(i, f) for i, f in enumerate(findings, start=1)]
    n = 0
    for p in analysis.parameters:
        n += 1
        unit = f" {p.unit}" if p.unit else ""
        items.append(EvidenceItem(
            id=f"P-{n:03d}",
            type="process_statistic",
            source="deterministic_process_analysis",
            description=(
                f"{p.label}: {p.start:g}{unit} at {p.start_time_hours:g} h → {p.final:g}{unit} at {p.final_time_hours:g} h "
                f"(min {p.minimum:g}, max {p.maximum:g}; {p.count} observation(s))."
            ),
            parameter=p.parameter,
            parameter_label=p.label,
            unit=p.unit,
            culture_time_start=p.start_time_hours,
            culture_time_end=p.final_time_hours,
            observed_value=p.final,
            previous_value=p.start,
            minimum=p.minimum,
            maximum=p.maximum,
        ))
    q = analysis.data_quality
    missing = [m.label for m in q.missing_values if m.missing]
    items.append(EvidenceItem(
        id=f"P-{n + 1:03d}",
        type="data_coverage",
        source="deterministic_process_analysis",
        description=(
            f"{q.observation_count} observation(s) at {q.distinct_time_points} distinct time point(s)"
            + (f" from {analysis.culture_start_hours:g} h to {analysis.culture_end_hours:g} h" if analysis.culture_end_hours is not None else "")
            + (f"; parameters with missing values: {', '.join(missing)}" if missing else "")
            + "."
        ),
        culture_time_start=analysis.culture_start_hours,
        culture_time_end=analysis.culture_end_hours,
    ))
    return items


def annotate_context(context: dict, evidence: list[EvidenceItem]) -> None:
    """Write the evidence IDs into the context Gemini receives (same order as build_evidence)."""
    findings = [e for e in evidence if e.type == "anomaly"]
    stats = [e for e in evidence if e.type == "process_statistic"]
    coverage = next(e for e in evidence if e.type == "data_coverage")
    for entry, item in zip(context["anomaly_detection"]["findings"], findings, strict=True):
        entry["evidence_id"] = item.id
    for entry, item in zip(context["process_analysis"]["parameter_statistics"], stats, strict=True):
        entry["evidence_id"] = item.id
    # sibling key: the data_coverage block itself stays identical to the Phase 5 analysis output
    context["process_analysis"]["data_coverage_evidence_id"] = coverage.id
    context["valid_evidence_ids"] = [e.id for e in evidence]


def filter_refs(refs: list[str], valid: set[str], rejected: list[str]) -> list[str]:
    """Keep known IDs (deduplicated, in order); collect unknown ones in ``rejected``."""
    kept: list[str] = []
    for ref in refs:
        ref = ref.strip().upper()
        if ref in valid:
            if ref not in kept:
                kept.append(ref)
        elif ref and ref not in rejected:
            rejected.append(ref)
    return kept


def referenced(evidence: list[EvidenceItem], refs: set[str]) -> list[EvidenceItem]:
    """The evidence items that were actually cited, in evidence order."""
    return [e for e in evidence if e.id in refs]
