"""Optional Gemini explanation of an already-generated experiment plan (Phase 16).

Gemini receives only the deterministic plan (reference values, constraints, candidates,
rationales, derived values, warnings, limitations) - never the raw observation history -
and must not calculate or change candidates.
"""

import json
from datetime import datetime, timezone

from pydantic import BaseModel, Field
from sqlmodel import Session

from . import gemini_service
from .db_models import ExperimentRow
from .gemini_service import Generator
from .planning import ExperimentPlan, PlanRequest, plan_experiment

CATEGORY = "AI INTERPRETATION"
NOTICE = (
    "AI-generated explanation of the deterministic candidate experiments. Candidates and values come from the "
    "application; review the explanation before relying on it."
)

SYSTEM_INSTRUCTION = """You explain candidate experiment conditions for a cell-culture bioprocess scientist.
The candidates were generated by the application's deterministic design rules and are the only source of numbers.

Rules:
- Use only the supplied plan. Do not invent measurements, results or ranges.
- Do not calculate, add, remove or modify candidates; quote the supplied values exactly, with units.
- Explain what each candidate tests and why it may be informative, framed as something to investigate.
- Never claim a candidate is optimal, the best, guaranteed, or that it will improve any outcome; no outcome is predicted.
- Do not claim causation; mention uncertainty (single reference run, small designs, missing parameters, extrapolation).
- Prototype default ranges are application defaults, not limits for a specific cell line.
- Do not provide unsafe biological or medical instructions; you do not control any bioreactor.
- Use concise, scientist-friendly language.

Output JSON matching the schema; give one explanation per supplied candidate id."""


class CandidateExplanation(BaseModel):
    candidate_id: str = Field(min_length=1, max_length=20)
    explanation: str = Field(min_length=1, max_length=2000)


class PlanInterpretation(BaseModel):
    candidate_explanations: list[CandidateExplanation] = Field(max_length=8)
    considerations: list[str] = Field(max_length=8)
    uncertainties: list[str] = Field(max_length=8)


class PlanInterpretationResponse(BaseModel):
    experiment_id: str
    provider: str = "Gemini"
    model: str
    generated_at: datetime
    category: str = CATEGORY
    notice: str = NOTICE
    interpretation: PlanInterpretation


def build_plan_context(plan: ExperimentPlan) -> dict:
    """The plan contains no observation history, only final reference values and derived candidate values."""
    return plan.model_dump(mode="json")


def build_prompt(context: dict) -> str:
    return (
        "EXPERIMENT PLAN (generated deterministically by the application; treat as fact; do not recalculate):\n"
        + json.dumps(context, indent=2, ensure_ascii=False)
    )


def interpret_plan(session: Session, row: ExperimentRow, request: PlanRequest, generate: Generator | None = None) -> PlanInterpretationResponse:
    plan = plan_experiment(session, row, request)
    interpretation = gemini_service.generate_structured(SYSTEM_INSTRUCTION, build_prompt(build_plan_context(plan)), PlanInterpretation, generate)
    return PlanInterpretationResponse(
        experiment_id=row.experiment_id,
        model=gemini_service.model_name(),
        generated_at=datetime.now(timezone.utc),
        interpretation=interpretation,
    )
