"""Experiment Planning (Phase 16): deterministic candidate conditions for the next experiment.

The reference is the final observed value of each controllable parameter of ONE stored
experiment. Candidates are small, standard exploration designs (baseline repeat,
one-at-a-time steps, range centre/low/high, a two-level comparison) inside allowed ranges.
Nothing here predicts a biological outcome, nothing is stored and Gemini is never called.
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from sqlmodel import Session

from .analysis import PARAMETER_DECIMALS, analyze_experiment
from .anomaly import DEFAULT_CONFIG, analyze_anomalies
from .db_models import ExperimentRow
from .models import Observation

CONTROLLABLE = ["temperature_c", "ph", "dissolved_oxygen_percent", "agitation_rpm", "aeration_rate", "feed_rate"]
DEFAULT_MAX_CANDIDATES = 5
MAX_CANDIDATES = 8
DEFAULT_STEP_FRACTION = {"improve_cell_density": 0.10, "maintain_stability": 0.05}
MAX_COMPARISON_FACTORS = 3  # 2 factors -> 2² = 4 runs; 3 factors -> 2^(3-1) = 4 runs

DISCLAIMER = (
    "Candidate experiments are suggested test conditions generated by simple, deterministic design rules within the "
    "allowed ranges. They are not predictions of biological outcome, are not validated for any cell line or "
    "bioreactor, and require scientific review before use. No experiment is created or changed."
)
LIMITATIONS = [
    "No biological outcome is predicted; candidates only describe which conditions to test.",
    "The reference is a single run; its final values may be noisy or unrepresentative.",
    "One-at-a-time designs do not reveal interactions between parameters.",
    "The two-level comparison design is very small and cannot separate every interaction.",
    "Prototype default ranges are generic application defaults, not limits for a specific cell line or process.",
    "Aeration and feed rate have no default range and are held at the reference unless a constraint is supplied.",
]
DERIVED_DEFINITIONS = [
    "change_from_reference = candidate value − reference value (final observed value).",
    "relative_position = (candidate value − allowed min) / (allowed max − allowed min); 0 = min, 1 = max.",
    "default step = fraction of the allowed range width (10 % for cell-density exploration, 5 % for stability).",
]
OBJECTIVE_LABELS = {
    "improve_cell_density": "Explore conditions related to cell density",
    "maintain_stability": "Maintain process stability",
    "explore_conditions": "Explore operating conditions",
    "compare_candidates": "Compare candidate conditions",
}

Objective = Literal["improve_cell_density", "maintain_stability", "explore_conditions", "compare_candidates"]


def _limits(name: str) -> tuple[float | None, float | None]:
    """Physical/definitional bounds declared on the Observation field (e.g. pH 0-14, rates >= 0)."""
    lower = upper = None
    for m in Observation.model_fields[name].metadata:
        lower = getattr(m, "ge", lower)
        upper = getattr(m, "le", upper)
    return lower, upper


def _meta(name: str) -> tuple[str, str | None]:
    field = Observation.model_fields[name]
    return field.title or name, (field.json_schema_extra or {}).get("unit")


# --- request -------------------------------------------------------------------------------------

class ParameterConstraint(BaseModel):
    model_config = ConfigDict(extra="forbid")

    min: float = Field(allow_inf_nan=False)
    max: float = Field(allow_inf_nan=False)
    step: float | None = Field(default=None, gt=0, allow_inf_nan=False)
    changeable: bool = Field(default=True, description="False holds the parameter at the reference.")

    @model_validator(mode="after")
    def _ordered(self):
        if self.min > self.max:
            raise ValueError("min must not exceed max")
        return self


class PlanRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    objective: Objective = "explore_conditions"
    constraints: dict[str, ParameterConstraint] = Field(default_factory=dict)
    max_candidates: int = Field(default=DEFAULT_MAX_CANDIDATES, ge=1, le=MAX_CANDIDATES)

    @field_validator("constraints")
    @classmethod
    def _known_and_within_limits(cls, value: dict[str, ParameterConstraint]):
        for name, c in value.items():
            if name not in CONTROLLABLE:
                raise ValueError(f"unknown parameter '{name}'; allowed: {', '.join(CONTROLLABLE)}")
            lower, upper = _limits(name)
            if (lower is not None and c.min < lower) or (upper is not None and c.max > upper):
                raise ValueError(f"{name}: range must stay within the observation limits ({lower} to {upper})")
        return value


# --- response ------------------------------------------------------------------------------------

class ReferenceValue(BaseModel):
    parameter: str
    label: str
    unit: str | None
    value: float | None
    observed_min: float | None
    observed_max: float | None
    category: Literal["OBSERVED DATA", "NOT AVAILABLE"]
    note: str | None = None


class ConstraintInfo(BaseModel):
    parameter: str
    label: str
    unit: str | None
    min: float | None
    max: float | None
    step: float | None
    step_source: str | None
    changeable: bool
    category: Literal["USER CONSTRAINT", "PLANNING ASSUMPTION", "NOT AVAILABLE"]
    note: str
    clamped: bool = False
    clamp_note: str | None = None


class Condition(BaseModel):
    parameter: str
    label: str
    unit: str | None
    value: float | None
    reference_value: float | None
    change_from_reference: float | None  # DERIVED CALCULATION
    relative_position: float | None  # DERIVED CALCULATION
    changed: bool
    extrapolation: bool  # outside the observed range of the reference run


class Candidate(BaseModel):
    id: str
    design_role: str
    category: Literal["CANDIDATE EXPERIMENT"] = "CANDIDATE EXPERIMENT"
    conditions: list[Condition]
    changed_parameters: list[str]
    rationale: list[str]
    warnings: list[str]


class ExperimentPlan(BaseModel):
    label: str = "Experiment Planning"
    disclaimer: str = DISCLAIMER
    experiment_id: str
    objective: Objective
    objective_label: str
    max_candidates: int
    message: str | None = None
    reference: list[ReferenceValue]
    constraints: list[ConstraintInfo]
    candidates: list[Candidate]
    candidates_omitted: int = 0
    derived_calculations: list[str] = DERIVED_DEFINITIONS
    warnings: list[str]
    assumptions: list[str]
    limitations: list[str] = LIMITATIONS


# --- calculation ---------------------------------------------------------------------------------

def _fmt(value: float, name: str) -> str:
    return f"{value:.{PARAMETER_DECIMALS[name]}f}"


def _unit(name: str) -> str:
    unit = _meta(name)[1]
    return f" {unit}" if unit else ""


def _reference(analysis) -> dict[str, ReferenceValue]:
    summaries = {p.parameter: p for p in analysis.parameters}
    out = {}
    for name in CONTROLLABLE:
        label, unit = _meta(name)
        s = summaries.get(name)
        if s is None:
            out[name] = ReferenceValue(parameter=name, label=label, unit=unit, value=None, observed_min=None, observed_max=None,
                                       category="NOT AVAILABLE", note="Not recorded in the reference experiment; no value is assumed.")
        else:
            out[name] = ReferenceValue(parameter=name, label=label, unit=unit, value=s.final, observed_min=s.minimum,
                                       observed_max=s.maximum, category="OBSERVED DATA", note=f"Final observed value at {s.final_time_hours:g} h.")
    return out


def _constraints(request: PlanRequest, reference: dict[str, ReferenceValue]) -> dict[str, ConstraintInfo]:
    out = {}
    fraction = DEFAULT_STEP_FRACTION.get(request.objective, 0.10)
    for name in CONTROLLABLE:
        label, unit = _meta(name)
        user = request.constraints.get(name)
        default = DEFAULT_CONFIG.ranges.get(name)
        if user is not None:
            lo, hi, step, changeable = user.min, user.max, user.step, user.changeable
            category, note = "USER CONSTRAINT", "Allowed range entered by the user."
        elif default is not None:
            lo, hi, step, changeable = default.min, default.max, None, True
            category, note = "PLANNING ASSUMPTION", "Prototype default range (application monitoring default, not a cell-line limit)."
        else:
            out[name] = ConstraintInfo(parameter=name, label=label, unit=unit, min=None, max=None, step=None, step_source=None,
                                       changeable=False, category="NOT AVAILABLE",
                                       note="No default range; held at the reference unless a range is entered.")
            continue
        step_source = "user" if step is not None else f"default: {fraction:.0%} of allowed range"
        if step is None:
            step = round((hi - lo) * fraction, PARAMETER_DECIMALS[name]) or None
        info = ConstraintInfo(parameter=name, label=label, unit=unit, min=lo, max=hi, step=step, step_source=step_source,
                              changeable=changeable, category=category, note=note)
        ref = reference[name].value
        if ref is not None and not lo <= ref <= hi:
            bound = lo if ref < lo else hi
            info.clamped = True
            info.clamp_note = (f"Reference {_fmt(ref, name)}{_unit(name)} is outside the allowed range; candidates start from "
                               f"{_fmt(bound, name)}{_unit(name)} (clamped).")
        out[name] = info
    return out


def _base(reference, constraints) -> dict[str, float | None]:
    """Starting conditions: the reference, clamped into each allowed range."""
    base = {}
    for name in CONTROLLABLE:
        ref, c = reference[name].value, constraints[name]
        base[name] = ref if ref is None or c.min is None else min(max(ref, c.min), c.max)
    return base


def _variable(constraints, reference, only_user: bool = False) -> list[str]:
    """Parameters that may be varied, in fixed order: range available, changeable, reference available."""
    return [
        n for n in CONTROLLABLE
        if constraints[n].min is not None and constraints[n].changeable and reference[n].value is not None
        and constraints[n].max > constraints[n].min and (not only_user or constraints[n].category == "USER CONSTRAINT")
    ]


def _condition(name, value, reference, constraints) -> Condition:
    label, unit = _meta(name)
    ref, c = reference[name], constraints[name]
    d = PARAMETER_DECIMALS[name]
    if value is None:
        return Condition(parameter=name, label=label, unit=unit, value=None, reference_value=None, change_from_reference=None,
                         relative_position=None, changed=False, extrapolation=False)
    value = round(value, d)
    change = round(value - ref.value, d)
    position = round((value - c.min) / (c.max - c.min), 3) if c.min is not None and c.max > c.min else None
    extrapolation = not (ref.observed_min <= value <= ref.observed_max)
    return Condition(parameter=name, label=label, unit=unit, value=value, reference_value=ref.value, change_from_reference=change,
                     relative_position=position, changed=change != 0, extrapolation=extrapolation)


def _describe(name, value, base_value) -> str:
    return f"{_meta(name)[0]} {_fmt(base_value, name)} → {_fmt(value, name)}{_unit(name)}"


def _designs(request, variable, base, constraints) -> list[tuple[str, dict, list[str]]]:
    """Returns (design_role, overrides of the base conditions, rationale) in deterministic order."""
    objective = request.objective
    designs = []
    if objective in ("improve_cell_density", "maintain_stability"):
        designs.append(("Baseline repeat", {}, [
            "Repeats the reference conditions to check run-to-run reproducibility before interpreting any change."]))
        purpose = ("Explores sensitivity of cell density to this parameter." if objective == "improve_cell_density"
                   else "Small change to check whether process behaviour stays similar to the reference.")
        for n in variable:
            c = constraints[n]
            if not c.step:
                continue
            for direction, value in (("lower", base[n] - c.step), ("higher", base[n] + c.step)):
                if c.min <= round(value, PARAMETER_DECIMALS[n]) <= c.max:
                    designs.append((f"One-at-a-time step ({direction} {_meta(n)[0]})", {n: value}, [
                        f"Changes {_describe(n, value, base[n])} only (step {_fmt(c.step, n)}); all other parameters held at the reference.",
                        purpose]))
    elif objective == "explore_conditions":
        centre = {n: (constraints[n].min + constraints[n].max) / 2 for n in variable}
        designs.append(("Centre of allowed ranges", centre, [
            "Places every variable parameter at the centre of its allowed range as a reference point for exploration."]))
        for n in variable:
            for label, value in (("low", constraints[n].min), ("high", constraints[n].max)):
                designs.append((f"Exploration point ({label} {_meta(n)[0]})", {**centre, n: value}, [
                    f"Moves {_meta(n)[0]} to the {label} end of its allowed range ({_fmt(value, n)}{_unit(n)}) with the other "
                    "variable parameters at their range centre; one parameter changed at a time.",
                    "Explores how process behaviour responds across the allowed range of this parameter."]))
    else:  # compare_candidates: two-level design over explicitly constrained parameters
        factors = variable[:MAX_COMPARISON_FACTORS]
        if factors:
            runs = [[a, b] for a in (0, 1) for b in (0, 1)] if len(factors) >= 2 else [[0], [1]]
            if len(factors) == 3:
                runs = [[a, b, a ^ b ^ 1] for a, b in runs]  # 2^(3-1) fractional design, C = A·B in ± coding
            for levels in runs:
                values = {n: (constraints[n].min if lv == 0 else constraints[n].max) for n, lv in zip(factors, levels)}
                text = ", ".join(f"{_meta(n)[0]} {'low' if lv == 0 else 'high'} ({_fmt(values[n], n)}{_unit(n)})" for n, lv in zip(factors, levels))
                designs.append(("Two-level comparison run", values, [
                    f"Sets {text}; other parameters held at the reference.",
                    "Part of a small two-level design so the constrained parameters can be compared side by side."]))
    return designs


def plan_experiment(session: Session, row: ExperimentRow, request: PlanRequest) -> ExperimentPlan:
    analysis = analyze_experiment(session, row)
    reference = _reference(analysis)
    constraints = _constraints(request, reference)
    warnings, assumptions = [], [
        "Prototype default ranges come from the application's monitoring configuration (PLANNING ASSUMPTION).",
        "Parameters without a range, or marked not changeable, are held at the reference value.",
    ]
    plan = dict(experiment_id=row.experiment_id, objective=request.objective, objective_label=OBJECTIVE_LABELS[request.objective],
                max_candidates=request.max_candidates, reference=list(reference.values()), constraints=list(constraints.values()),
                assumptions=assumptions)
    if analysis.observation_count == 0:
        return ExperimentPlan(**plan, candidates=[], warnings=[],
                              message="The reference experiment has no observations, so no reference conditions are available and no candidates are generated.")

    anomalies = analyze_anomalies(session, row)
    if anomalies.counts.significant:
        warnings.append(f"The reference experiment has {anomalies.counts.significant} significant anomaly finding(s); "
                        "a baseline repeat may be appropriate before changing conditions.")
    for c in constraints.values():
        if c.clamped:
            warnings.append(c.clamp_note)

    base = _base(reference, constraints)
    variable = _variable(constraints, reference, only_user=request.objective == "compare_candidates")
    if request.objective == "compare_candidates":
        if not variable:
            warnings.append("Enter an allowed range (min < max) for at least one changeable parameter to build a comparison design.")
        elif len(variable) > MAX_COMPARISON_FACTORS:
            warnings.append(f"Only the first {MAX_COMPARISON_FACTORS} constrained parameters are compared: "
                            f"{', '.join(_meta(n)[0] for n in variable[:MAX_COMPARISON_FACTORS])}.")

    candidates, seen = [], set()
    for role, overrides, rationale in _designs(request, variable, base, constraints):
        values = {**base, **overrides}
        conditions = [_condition(n, values[n], reference, constraints) for n in CONTROLLABLE]
        key = tuple(c.value for c in conditions)
        if key in seen:
            continue  # an identical set of conditions is only suggested once
        seen.add(key)
        cand_warnings = [
            f"Extrapolation beyond observed conditions: {c.label} {_fmt(c.value, c.parameter)}{_unit(c.parameter)} is outside the "
            f"observed range {_fmt(reference[c.parameter].observed_min, c.parameter)}–{_fmt(reference[c.parameter].observed_max, c.parameter)}"
            f"{_unit(c.parameter)} of the reference run."
            for c in conditions if c.extrapolation
        ]
        candidates.append((role, conditions, rationale, cand_warnings))
    omitted = max(0, len(candidates) - request.max_candidates)
    result = [
        Candidate(id=f"C{i}", design_role=role, conditions=conds, changed_parameters=[c.parameter for c in conds if c.changed],
                  rationale=rationale, warnings=w)
        for i, (role, conds, rationale, w) in enumerate(candidates[: request.max_candidates], start=1)
    ]
    return ExperimentPlan(**plan, candidates=result, candidates_omitted=omitted, warnings=warnings)
